manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dxue
      url-base: https://github.com/dxue
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-auto-layer
      remote: dxue
      # ブランチ名ではなく、特定のコミットを指定して安定させます
      revision: d32766f65839b66c40689e472251a37c093a129f 
